version: '3.9'
services:
  app:
    image: node:18  # Mudar versao do node
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    ports:
      - "8080:8080"
    environment:
     - DB_USER=root
     - DB_PASS=password
     - DB_NAME=taxi_db
     - DB_HOST=db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password