version: '3.9'
services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./.env:/app/.env
    command: sh -c "npm install && npx sequelize db:create && npx sequelize db:migrate:undo:all && npx sequelize db:migrate && npx sequelize-cli db:seed:all && npm run start:dev"
    ports:
      - "8080:8080"
    environment:
     - DB_USER=root
     - DB_PASS=password
     - DB_NAME=taxi_db
     - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 10
      interval: 2s
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules